Implementing BFS algorithm and graph to fix the nerdy bug of map update.
UoB-COMSM0110/2024-group-1 pull request #62
Opened 2024-04-12 21:36 UTC by RicardoMiles

Using a breadth-first algorithm and the graph's data structure to fix the nerdy effect of making all nodes above the current level clickable when the map is updated, by updating only those nodes on connected bypass roads to be clickable ( Of course the premise is all that their level gap is less than AP, that hasn't changed ) .

2024-04-12 21:42 UTC, RicardoMiles commented
Hi team!@A-PS1999 @erer1022 @JThakral20 @Doctor-TOTORO 
Using a breadth-first algorithm and the graph's data structure to fix the nerdy effect of making all nodes above the current level clickable when the map is updated, by updating only those nodes on connected bypass roads to be clickable ( Of course the premise is all that their level gap is less than AP, that hasn't changed ) .

Now the whole map can basically be said to be self-updating when nodes are clicked, every time. Returning from endstate requires only updates of AP value and a couple of additional public method calls (which provided in MapState.pde) to edit the .json file. We don't even have to do anything when returning from ShopState, just call the constructor of MapState!

2024-04-13 08:28 UTC, A-PS1999 requested changes
Hey Ricardo, I think there's a flaw here. As you can see from the below screenshot, all the levels at the bottom are blocked, whereas every higher level is free. This, to me, seems to be the reverse of what it should be. It seems that the player or the green selection circle defaults to starting at the very top, which is probably affecting this issue.

![Screenshot 2024-04-13 092040](https://github.com/UoB-COMSM0110/2024-group-1/assets/74210324/0e6de370-343a-4683-b9b9-ea052f870e20)
My understanding was that the player would start somewhere at the bottom, with the goal being to move up.

2024-04-13 09:43 UTC, RicardoMiles commented
Hey Sam@A-PS1999 
There is some misunderstanding here, this phenomenon is actually due to the existence of mapTemp.JSON in our library now, the mapTemp.json in the library is the map state that was updated and stored after you last clicked on the bottom node, which was uploaded by your last merge. It's likely because it was uploaded along with the report, and I actually updated .gitignore to prevent the upload, but your local .gitignore should be ignoring the .gitignore itself, so it won't synchronize with the ignore setting. If you delete mapTemp.JSON, and re-enter it you'll see that by default when you first enter the map the bottom row of nodes are clickable, but not the rest, and the subsequent ones are updated based on the AP and the selected branch.

2024-04-13 09:57 UTC, A-PS1999 approved these changes
Hey @RicardoMiles, thanks for pointing that out. I tried again and it is indeed as you say.

So basically, it's alright to delete mapTemp.json from main or any other branches? Just checking in case this issue crops up again.

2024-04-13 09:58 UTC, merged

2024-04-13 10:12 UTC, RicardoMiles commented
@A-PS1999 Yep！ It is wise to delete mapTemp.json from ```main``` and ```endState-mapState-flow```
By the way, I will try my best to notify other mates that their local .gitignore included the rules of mapTemp.json.
I apologize that it was an oversight on my part before, forgetting that everyone's local .gitignore could potentially put itself on ignore, so I will leave the ignore setting unupdated.
Also thank you very much, please keep this branch going, Lanai is working on it!